version: '3.8'

services:
  # 1. Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: wpex_admin
      POSTGRES_DB: wpex_keys_db
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - wpex_db_data:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - wpex-network
    deploy:
      replicas: 1

  # 2. Manager GUI (Streamlit)
  manager:
    image: python:3.9-slim
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      DB_HOST: db
      DB_NAME: wpex_keys_db
      DB_USER: wpex_admin
      WPEX_NETWORK: wpex_wpex-network
    networks:
      - wpex-network
    secrets:
      - db_password
      - db_encryption_key
      - jwt_secret
    working_dir: /app
    command: >
      bash -c "pip install streamlit docker psycopg2-binary extra-streamlit-components PyJWT && 
      streamlit run manager.py --server.port 8501 --server.address 0.0.0.0"
    deploy:
      placement:
        constraints: [node.role == manager]

  # 3. Reverse Proxy (Nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wpex-network
    depends_on:
      - manager
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  wpex-network:
    driver: overlay
    attachable: true

volumes:
  wpex_db_data:

secrets:
  db_password:
    external: true
  db_encryption_key:
    external: true
  jwt_secret:
    external: true

