services:
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password
      - --innodb_buffer_pool_size=256M
      - --innodb_log_file_size=64M
      - --max_connections=50
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - zabbix_db_data:/var/lib/mysql
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Europe/Rome
    depends_on:
      zabbix-db:
        condition: service_healthy
      zabbix-server:
        condition: service_started
    ports:
      - "8080:8080"
    mem_limit: 256m
    restart: unless-stopped

  # ── Zabbix Agent 2 ────────────────────────────────────────────────────
  # Monitora tutti i container Docker via socket + raggiunge i container
  # wpex-test tramite la rete condivisa "monitoring".
  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-6.0-latest
    container_name: zabbix-agent2
    user: root
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: "10051"
      ZBX_HOSTNAME: "Docker-Host"
      ZBX_PASSIVE_ALLOW: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - zabbix-server
    networks:
      default:
      monitoring:
    mem_limit: 64m
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
      ZBX_STARTPOLLERS: 2
      ZBX_STARTPINGERS: 1
      ZBX_STARTPREPROCESSORS: 2
      ZBX_STARTDBSYNCERS: 2
    depends_on:
      zabbix-db:
        condition: service_healthy
    ports:
      - "10051:10051"
    networks:
      default:
      monitoring:
    mem_limit: 256m
    restart: unless-stopped

volumes:
  zabbix_db_data:

networks:
  monitoring:
    external: true
    name: wpex_monitoring
